(()=>{
  if(typeof API==='undefined'||typeof load!=='function'||typeof authHeaders!=='function')return;
  const tabs=document.getElementById('viewTabs'),hub=document.getElementById('regularHub');if(!tabs||!hub)return;
  const button=document.createElement('button');button.type='button';button.id='binboNekoBtn';button.className='push-button small';button.dataset.view='binbo-neko';button.textContent='貧乏ねこ';const refreshAnchor=tabs.querySelector('#refreshBtn');if(refreshAnchor)refreshAnchor.before(button);else tabs.append(button);
  const nav=document.getElementById('ccPrimaryNav');if(nav){const b=document.createElement('button');b.type='button';b.className='push-button home-nav-button';b.dataset.homeAction='binbo-neko';b.textContent='貧乏ねこ';b.onclick=()=>load('binbo-neko');nav.querySelector('[data-home-action="more"]')?.before(b);}
  const desk=document.createElement('section');desk.id='binboNekoDesk';desk.hidden=true;desk.setAttribute('aria-label','貧乏ねこの投稿原稿');hub.append(desk);
  const state={data:null,busy:false,filter:'ready'};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=v=>v?new Date(v).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'}):'未確認';
  const yen=v=>Number.isInteger(v)?v.toLocaleString('ja-JP')+'円':'未確認';
  const notice=(message,bad=false)=>{if(typeof toast==='function')toast(message,bad?'bad':undefined);else desk.querySelector('[role="status"]').textContent=message;};
  async function api(body){const r=await fetch(API,{method:'PATCH',headers:{...authHeaders(),'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.status===401){authExpired();throw new Error('ログインを確認してください')}const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'操作できませんでした');return d;}
  function show(){
    window.CCX?.hide?.();window.CCReddit?.hide?.();window.CCHome?.leave?.();if(window.CCHome)window.CCHome.active=false;
    document.getElementById('mainWindow')?.classList.remove('home-active');document.body.classList.remove('home-mode','x-mode');
    ['commandHome','sourcingHub','affiliateDesk'].forEach(id=>document.getElementById(id)?.setAttribute('hidden',''));
    document.getElementById('homeViewBtn')?.classList.remove('selected');hub.hidden=false;document.getElementById('domainTabs').hidden=true;
    document.getElementById('list').hidden=true;hub.querySelector('.section-title').hidden=true;document.getElementById('listFilter').hidden=true;desk.hidden=false;
    tabs.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('selected',b.dataset.view==='binbo-neko');b.setAttribute('aria-pressed',String(b.dataset.view==='binbo-neko'))});window.CCNavigation?.focusPage?.();
  }
  async function refresh(){
    if(state.busy)return;state.busy=true;const button=document.getElementById('refreshBtn');button.disabled=true;
    try{const r=await fetch(API+'?resource=binbo-neko',{headers:authHeaders(),cache:'no-store',signal:AbortSignal.timeout(25000)});if(r.status===401){authExpired();return}const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'原稿を読み込めませんでした');state.data=d;render();}
    catch(e){desk.innerHTML=`<div class="empty"><b>原稿を読み込めませんでした</b><p>${esc(e.message)}</p><button type="button" class="push-button" data-retry>再読込</button></div>`;desk.querySelector('[data-retry]').onclick=refresh;}
    finally{state.busy=false;button.disabled=false;}
  }
  function card(j){
    const p=j.product||{},o=j.offer||{},fit=j.fit||{},copy=j.copy||{},ready=['ready','copied'].includes(j.state_key);
    return `<article class="neko-card"><header><span class="neko-state neko-${esc(j.state_key)}">${esc(j.state_label)}</span><h3>${esc(copy.title||p.name||'条件の確認待ち')}</h3></header><p class="neko-identity">${esc(p.brand)}｜${esc(p.color||'色未確認')} ${esc(p.size||'')}｜${esc(p.condition||'状態未確認')}</p><p class="neko-price">送料込み <strong>${yen(o.payable_yen)}</strong><small>商品 ${yen(o.price_yen)} ＋ 送料 ${yen(o.shipping_yen)}</small></p><p class="neko-fit">${esc(fit.reason||'紹介する理由を自動で確認しています。')}</p><div class="neko-actions"><button type="button" class="push-button" data-packet="${esc(j.id)}" ${ready?'':'disabled'}>AIへ渡す一式をコピー</button><a class="push-button neko-shop" href="${esc(/^https:\/\//.test(o.url||'')?o.url:'#')}" target="_blank" rel="noopener noreferrer">販売ページ</a></div>${j.issues?.length?`<details class="neko-warning"><summary>確認待ちの理由（${j.issues.length}件）</summary><ul>${j.issues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`:''}<details class="neko-copy"><summary>原稿とページ構成を見る（${copy.pages?.length||0}枚）</summary><p><b>誰に：</b>${esc(fit.reader)}<br><b>用途：</b>${esc(fit.use)}</p>${(copy.pages||[]).map(s=>`<section><h4>${s.page}枚目｜${esc(s.headline)}</h4><p>${esc(s.body)}</p><small>見せ方：${esc(s.visual_intent)}</small></section>`).join('')}<h4>Threads</h4><pre>${esc(copy.threads_caption)}</pre><h4>TikTok</h4><pre>${esc(copy.tiktok_caption)}</pre><h4>注意点</h4><ul>${(fit.cautions||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details><details class="neko-evidence"><summary>根拠・元の仕入れ判断</summary><p>元の状態：${esc(j.source_judgment?.verdict||'未確認')}<br>購入しなかった理由：${esc(j.source_judgment?.reason||'不明（記録なし）')}<br>購入照合：${esc(j.source_judgment?.purchase_check||'未確認')}</p><ul>${(j.evidence||[]).map(e=>`<li>${esc(e.claim)} <a href="${esc(/^https:\/\//.test(e.url||'')?e.url:'#')}" target="_blank" rel="noopener noreferrer">根拠</a>（${date(e.checked_at)}）</li>`).join('')}</ul><small>元商品ID：${esc(j.source_id)}<br>投稿ID：${esc(j.id)}</small></details><footer><small>販売条件の確認：${date(o.checked_at)}</small><div><button type="button" class="push-button small" data-recheck="${esc(j.id)}">再確認へ戻す</button><button type="button" class="push-button small" data-skip="${esc(j.id)}" ${j.state_key==='skipped'?'disabled':''}>今回は見送る</button></div></footer></article>`;
  }
  function render(){
    const d=state.data,jobs=d.jobs||[],counts={ready:0,waiting:0,copied:0,closed:0};jobs.forEach(j=>counts[['skipped','ended'].includes(j.state_key)?'closed':j.state_key]++);
    const names={ready:'届いた原稿',waiting:'確認待ち',copied:'コピー済み',closed:'終了・見送り',all:'すべて'};
    const selected=jobs.filter(j=>state.filter==='all'||(state.filter==='closed'?['skipped','ended'].includes(j.state_key):j.state_key===state.filter));
    const run=d.last_run,task=d.task;
    const runLabel=run?.trigger==='implementation_verification'?'試運転':'定期確認';
    desk.innerHTML=`<header class="neko-header"><div><h2>貧乏ねこ</h2><p>好きなブランドを安く買いたい</p></div><span class="neko-operation">写真と原稿をAIへ渡す → 完成物を確認 → 自分で投稿</span></header><p class="neko-run">定期制作：${task?.is_enabled?'稼働設定済み':'設定を確認中'}　${run?''+runLabel+' '+date(run.finished_at)+' ／ 原稿 '+(run.created_count||0)+'件・更新 '+(run.updated_count||0)+'件':'実行記録はまだありません'}<small>広告リンクは投稿前に本人が発行。原稿の自動準備は、条件が揃う商品のみ。</small></p><div class="neko-filters" role="group" aria-label="原稿の状態">${Object.entries(names).map(([key,name])=>`<button type="button" class="push-button small ${state.filter===key?'selected':''}" aria-pressed="${state.filter===key}" data-filter="${key}">${name} ${key==='all'?jobs.length:counts[key]}</button>`).join('')}</div><p class="neko-status" role="status" aria-live="polite"></p><div class="neko-cards">${selected.length?selected.map(card).join(''):`<div class="empty"><b>${state.filter==='ready'?'今、制作へ渡せる原稿はありません':'この状態の原稿はありません'}</b><p>${state.filter==='ready'&&counts.copied?'コピー済みの原稿は「コピー済み」から開けます。':'候補がない回は投稿なしで正常です。普段の仕入れ記録だけを確認します。'}</p>${run?.notes?.length?`<ul>${run.notes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</div>`}</div>`;
    desk.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render();});
    desk.querySelectorAll('[data-packet]').forEach(b=>b.onclick=async()=>{const j=jobs.find(x=>x.id===b.dataset.packet);b.disabled=true;try{const r=await api({action:'neko_packet',id:j.id,revision:j.revision});try{await navigator.clipboard.writeText(r.packet);}catch{copyFallback(r.packet);notice('コピー欄を表示しました。全選択済みの文章をコピーしてください。');return;}await api({action:'neko_copied',id:j.id,revision:j.revision});notice('コピーしました。商品写真と一緒にAIへ渡してください。');state.filter='copied';await refresh();}catch(e){notice(e.message,true);}finally{b.disabled=false;}});
    for(const action of ['skip','recheck'])desk.querySelectorAll('[data-'+action+']').forEach(b=>b.onclick=async()=>{const j=jobs.find(x=>x.id===b.dataset[action]);b.disabled=true;try{await api({action:'neko_'+action,id:j.id,revision:j.revision});notice(action==='skip'?'紹介用の原稿を見送りにしました。':'次の定期制作で条件を再確認します。');await refresh();}catch(e){notice(e.message,true);b.disabled=false;}});
  }
  function copyFallback(text){const existing=document.getElementById('nekoCopyDialog');existing?.remove();const dialog=document.createElement('dialog');dialog.id='nekoCopyDialog';dialog.innerHTML='<p>この一式をコピーし、商品写真と一緒にAIへ渡してください。</p><textarea aria-label="AIへ渡す制作セット" readonly></textarea><button type="button" class="push-button">閉じる</button>';dialog.querySelector('textarea').value=text;document.body.append(dialog);dialog.querySelector('button').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.showModal();dialog.querySelector('textarea').select();}
  const previous=load;load=async function(view=app.view,...args){if(view==='binbo-neko'){app.view=view;show();await refresh();return;}desk.hidden=true;return previous.call(this,view,...args);};
  window.CCBinboNeko={state,refresh,show:()=>load('binbo-neko')};
})();
