'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const M=require('./chat-editorial-career-20260918.js');
function fixture(){return {id:'task:'+M.CAREER+':career-large:fixture',score:90,reviewState:'new',title:'応募する前に一つ確認',payload:{logical_task_id:M.CAREER,category:'career_large',content_type:'career_post_candidate',execution_source:'chat',editor_contract_version:M.VERSION,draft_revision:'r1',draft_status:'ready',post_title:'応募条件を一つ確かめる',caption:'募集要項の必須条件を確認する。出典：公式採用資料。',draft_slides:Array.from({length:7},(_,i)=>({page:i+1,headline:'何を確かめる？',body:'自分の経験を一つ照らす。',source_refs:['F1']})),draft_sources:[{id:'F1',url:'https://example.com/recruit',label:'公式採用情報',claim:'対象の募集要項を確認する'}],research_threads:[1,2].map(i=>({id:'T'+i,url:'https://girlschannel.net/topics/'+i+'/',title:'内部専用タイトル',checked_at:'2026-09-18',checked_scope:'元投稿と1〜20番を確認',comments:[{comment_no:1,summary:'内部専用の疑問',direct_url:'https://girlschannel.net/comment/'+i+'/1/',plus:null,minus:0}]})),demand_evidence:{verdict:'strong'},synthesis:{derived_question:'自分は応募できるか',connection:'応募不安と条件確認を結ぶ'},page_reflections:Array.from({length:7},(_,i)=>({page:i+1,origin:i<3?'synthesis':'editorial_extension',extracted:'疑問の構造',transformed:'自分の確認に変換',thread_refs:[],primary_source_refs:['F1']})),executable_action:{what:'募集要項を1件見る',where:'企業の公式採用ページ',check:'必須要件',decision:'自分の経験に該当するか'},editorial_review:{version:M.VERSION,status:'passed',unresolved_items:[],checks:Object.fromEntries(['two_threads','source_trace','public_separation','primary_alignment','practical_options','executable_action','cross_page_consistency','voice'].map(k=>[k,'passed']))},final_review:{status:'passed',draft_revision:'r1',reviewed_revision:'r1',unresolved_items:[]},production_spec:{size:'1080×1350',ratio:'4:5',individual_images:true},design_direction:'editorial',color_palette:'blue',cover_mode:'type_only',screenshot_decisions:{SS1:'user'},screenshot_requests:[],image_ready:true}};}
test('valid career fixture passes and public package excludes internal data',()=>{const r=fixture();assert.deepEqual(M.issues(r),[]);const p=JSON.stringify(M.publicPackage(r));assert.doesNotMatch(p,/girlschannel|内部専用|research_threads|page_reflections/);assert.match(M.bundle(r),/個別|独立/);});
test('design and screenshot ownership are preserved without copying the payload wholesale',()=>{const r=fixture();r.payload.private_note='INTERNAL_SECRET';assert.equal(M.publicPackage(r).design.design_direction,'editorial');assert.match(M.bundle(r),/"SS1":"user"/);assert.doesNotMatch(M.bundle(r),/INTERNAL_SECRET/);});
test('Work rows are outside scope even with copied contract metadata',()=>{const r=fixture();r.payload.execution_source='work';assert.equal(M.lane(r),'');assert.equal(M.applies(r),false);});
test('Money Chat is outside scope',()=>{const r=fixture();r.payload.category='fp_psychology';r.payload.content_type='fp_post_candidate';assert.equal(M.lane(r),'');});
test('Home Chat matches, legacy Home still not subject to new contract',()=>{const r=fixture();r.id='task:'+M.HOME+':house:test';Object.assign(r.payload,{logical_task_id:M.HOME,category:'house_living',content_type:'house_post_candidate'});assert.equal(M.lane(r),'house');assert.equal(M.applies(r),true);delete r.payload.editor_contract_version;assert.equal(M.applies(r),false);});
test('run summary never appears as career candidate',()=>{const r=fixture();r.payload.result_kind='run_summary';assert.equal(M.lane(r),'');});
test('career type must also match its own logical task',()=>{const r=fixture();r.payload.logical_task_id='another-task';assert.equal(M.lane(r),'');});
test('only one thread blocks readiness',()=>{const r=fixture();r.payload.research_threads.pop();assert.match(M.issues(r).join('|'),/別トピック2本/);assert.throws(()=>M.bundle(r));});
test('AMP and query variants of same GirlsChannel topic count as one',()=>{const r=fixture();r.payload.research_threads[1].url='https://girlschannel.net/topics/amp/1/?utm_source=test';assert.match(M.issues(r).join('|'),/別トピック2本/);});
test('non-GirlsChannel URL is not miscounted as a demand thread',()=>{assert.equal(M.threadKey('https://other.example/topics/1/'),'');});
test('unverified comments block readiness',()=>{const r=fixture();r.payload.research_threads[1].comments=[];assert.match(M.issues(r).join('|'),/実読範囲/);});
test('weak demand and low score block readiness',()=>{const r=fixture();r.payload.demand_evidence.verdict='medium';r.score=79;assert.match(M.issues(r).join('|'),/strong/);assert.match(M.issues(r).join('|'),/80点/);});
test('missing page map and page numbering error block readiness',()=>{const r=fixture();r.payload.page_reflections.pop();r.payload.draft_slides[0].page=2;const e=M.issues(r).join('|');assert.match(e,/反映表/);assert.match(e,/ページ順/);});
test('broken source reference blocks readiness',()=>{const r=fixture();r.payload.draft_slides[0].source_refs=['UNKNOWN'];assert.match(M.issues(r).join('|'),/一次情報参照/);});
test('large vague action without where/check/decision is insufficient',()=>{const r=fixture();r.payload.executable_action={what:'調べてみよう'};assert.match(M.issues(r).join('|'),/小さな一手/);});
test('all eight checks and current revision are required',()=>{const r=fixture();r.payload.editorial_review.checks.voice='pending';r.payload.draft_revision='r2';const e=M.issues(r).join('|');assert.match(e,/編集基準/);assert.match(e,/現行版/);});
test('public comment attribution is blocked in all copied fields',()=>{for(const key of ['post_title','caption']){const r=fixture();r.payload[key]='コメントではこうあった';assert.throws(()=>M.publicPackage(r));}const r=fixture();r.payload.draft_slides[0].visual='ガルちゃん画面';assert.throws(()=>M.publicPackage(r));});
test('unsafe URL cannot be made into a source link',()=>{const r=fixture();r.payload.draft_sources[0].url='javascript:alert(1)';assert.throws(()=>M.publicPackage(r));assert.equal(M.safeUrl('javascript:alert(1)'),'');});
test('missing assets do not fail script audit but block image handoff',()=>{const r=fixture();r.payload.image_ready=false;assert.deepEqual(M.issues(r),[]);assert.throws(()=>M.bundle(r),/素材の準備待ち/);});
test('required screenshot must actually be obtained',()=>{const r=fixture();r.payload.screenshot_requests=[{id:'SS1',url:'https://example.com/proof',required:true,acquisition_status:'pending'}];assert.throws(()=>M.bundle(r),/必須スクショ/);r.payload.screenshot_requests[0].acquisition_status='provided';assert.doesNotThrow(()=>M.bundle(r));});
test('private reflection UI safely escapes markup and unknown votes',()=>{const r=fixture();r.payload.research_threads[0].title='<img src=x onerror=alert(1)>';const h=M.internalHtml(r);assert.doesNotMatch(h,/<img/);assert.match(h,/&lt;img/);assert.match(h,/＋未確認／−0/);});
test('helpers parse string payloads and prefixed signal IDs',()=>{assert.deepEqual(M.payload({payload:'{"ok":true}'}),{ok:true});assert.deepEqual(M.payload({payload:'bad'}),{});assert.equal(M.taskId({id:'sns:task:abc:xyz'}),'abc');assert.deepEqual(M.unwrap({items:[1]}),[1]);});
function harness(input=[]){
 const els=new Map(),listeners={};
 function element(tag='div'){return {tag,dataset:{},classList:{remove(){},add(){}},hidden:false,textContent:'',innerHTML:'',children:[],setAttribute(k,v){this[k]=v;},querySelector(){return null;},appendChild(x){this.children.push(x);return x;},insertBefore(x){this.children.push(x);},addEventListener(k,fn){this[k]=fn;}};}
 for(const id of ['viewTabs','list','mainWindow','commandHome','sourcingHub','domainTabs','regularHub','refreshBtn','listFilter','listCaption','visibleCount','kpiLabelCount','kpiCount','kpiLabelS','kpiS','kpiLabelImpact','kpiImpact','kpiLabelStored','kpiStored'])els.set(id,element());
 const requests=[],d={getElementById:id=>els.get(id)||null,createElement:element,head:element('head'),body:element('body'),addEventListener:(n,fn)=>{listeners[n]=fn;}};
 const ctx={URL,console,document:d,app:{view:'active',busy:false,items:[]},API:'/api/command-center',authHeaders:()=>({Authorization:'Bearer fixture-only'}),load:function(v){ctx.oldCalls.push(v);return 'old:'+v;},cardHtml:r=>'<article class="thread">'+M.esc(r.title)+'</article>',setSelected(){},setStatus(){},showLoading(){},renderList(){els.get('list').innerHTML=ctx.app.items.map(r=>ctx.cardHtml(r,0)).join('');},oldCalls:[],fetch:async(url,opt)=>{requests.push({url,opt});if(ctx.error)throw Error('fixture failure');return {ok:true,status:200,json:async()=>({ok:true,items:input,storedCount:input.length})};},navigator:{clipboard:{writeText:async()=>{}}}};
 ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(require.resolve('./chat-editorial-career-20260918.js'),'utf8'),ctx);return {ctx,els,requests};
}
test('UI installs once and preserves all other view loads',async()=>{const {ctx,els,requests}=harness();assert.equal(els.get('viewTabs').children.length,1);assert.equal(ctx.CCChatEditorial.install(ctx),false);assert.equal(await ctx.load('house'),'old:house');assert.equal(await ctx.load('fp'),'old:fp');assert.equal(requests.length,0);});
test('career UI uses authenticated read only, filters fixtures, preserves user decision state',async()=>{const row=fixture();row.reviewState='accepted';const work=fixture();work.payload.execution_source='work';const before=JSON.stringify([row,work]);const {ctx,els,requests}=harness([row,work]);await ctx.load('career');assert.equal(ctx.app.items.length,1);assert.equal(requests[0].opt.headers.Authorization,'Bearer fixture-only');assert.equal(requests[0].opt.method,undefined);assert.match(els.get('list').innerHTML,/原稿・内部確認/);assert.doesNotMatch(els.get('list').innerHTML,/data-action="accepted"/);assert.equal(JSON.stringify([row,work]),before);assert.equal(ctx.app.busy,false);});
test('empty career and network error are shown honestly',async()=>{const {ctx,els}=harness();await ctx.load('career');assert.match(els.get('list').innerHTML,/まだありません/);ctx.error=true;await ctx.load('career');assert.match(els.get('list').innerHTML,/取得失敗/);assert.equal(ctx.app.busy,false);});
