const test=require('node:test'),assert=require('node:assert/strict');
const M=require('./v230-request-progress.js');
const now=Date.parse('2026-10-04T08:00:00Z');
const event=(status='running',extra={})=>({taskId:M.taskId,title:'テスト依頼',summary:'実作業を開始',payload:{kind:'request_progress',version:1,request_id:'request-test',status,priority:1,observed_at:'2026-10-04T07:45:00Z',last_progress_at:'2026-10-04T07:40:00Z',valid_until:'2026-10-04T09:45:00Z',next_action:'確認を進める',...extra}});
test('all six explicit statuses are supported, plus unknown',()=>assert.deepEqual(Object.values(M.labels),['受付','待機','作業中','私の確認待ち','問題で停止','完了','状況不明']));
test('running requires recent explicit execution evidence; fetching cannot refresh it',()=>{assert.equal(M.normalize(event(),{now}).status,'running');assert.equal(M.normalize(event(),{now:now+3*3600000}).status,'unknown');assert.equal(M.normalize(event('running',{valid_until:null}),{now}).status,'unknown');assert.equal(M.normalize(event('running',{valid_until:'2026-11-01T00:00:00Z'}),{now}).status,'unknown')});
test('progress time is independent from observation and unknown timestamps stay empty',()=>{const x=M.normalize(event('waiting',{last_progress_at:null}),{now});assert.equal(x.status,'waiting');assert.equal(x.progressAt,null);assert.equal(x.observedAt,'2026-10-04T07:45:00Z')});
test('source failure marks cached records unknown and preserves task details',()=>{const x=M.normalize(event(),{now,sourceError:true});assert.equal(x.status,'unknown');assert.match(x.reason,/前回記録：作業中/);assert.equal(x.nextAction,'確認を進める')});
test('completion needs a safe artifact and matching passed verification',()=>{assert.equal(M.normalize(event('completed'),{now}).status,'unknown');const p={artifacts:[{label:'確認結果',url:'https://example.com/result'}],verification:{status:'passed',checked_at:'2026-10-04T07:50:00Z',url:'https://example.com/result'}};assert.equal(M.normalize(event('completed',p),{now}).status,'completed');assert.equal(M.normalize(event('completed',{...p,recurring:true}),{now}).status,'unknown');assert.equal(M.normalize(event('completed',{...p,verification:{...p.verification,url:'https://example.com/other'}}),{now}).status,'unknown')});
test('review and stopped tasks sort first, then highest priority',()=>{const statuses=['waiting','running','blocked','needs_review','unknown'];const e=statuses.map((s,i)=>event(s,{request_id:'request-'+i,priority:5}));e.push(event('running',{request_id:'request-important',priority:1}));assert.deepEqual(M.rows(e,{now}).map(x=>x.id),['request-3','request-2','request-4','request-important','request-1','request-0'])});
test('foreign events and malformed records cannot appear as requests',()=>{assert.equal(M.normalize({...event(),taskId:'other'},{now}),null);assert.equal(M.normalize(event('running',{version:2}),{now}),null);assert.equal(M.normalize(event('running',{request_id:'<script>'}),{now}),null);assert.equal(M.normalize(event('running',{observed_at:null}),{now}).status,'unknown')});
test('latest observation wins without altering source',()=>{const a=event('waiting'),b=event('running',{observed_at:'2026-10-04T07:55:00Z'}),before=JSON.stringify([a,b]);assert.equal(M.rows([a,b],{now})[0].status,'running');assert.equal(JSON.stringify([a,b]),before)});
test('unsafe or credential-bearing links are excluded and text is escaped',()=>{for(const url of ['javascript:alert(1)','data:text/html,x','https://user:pass@example.com/','http://example.com/'])assert.equal(M.safeUrl(url),null);assert.equal(M.normalize(event('waiting',{artifacts:[{url:'javascript:alert(1)'}]}),{now}).artifacts.length,0);assert.equal(M.escape('<img src=x onerror="x">'),'&lt;img src=x onerror=&quot;x&quot;&gt;')});

const fs=require('node:fs');let JSDOM;try{({JSDOM}=require('/tmp/command-center-test/node_modules/jsdom'))}catch{}
const setup=()=>{const d=new JSDOM('<main id="commandHome"><section class="home-workspaces"></section></main><button id="menuTasks">監視</button><div id="taskModal"><div id="taskModalTitle"></div><div class="task-body"><div class="task-legend"></div><div><small>稼働中</small><b id="taskEnabled"></b></div><div id="taskRows"></div></div></div>',{runScripts:'outside-only',url:'https://example.test/',pretendToBeVisual:true});const w=d.window;w.CCHome={};w.API='https://example.test/api';w.authHeaders=()=>({Authorization:'Bearer test'});w.AbortController=AbortController;return d};
test('DOM integrates into existing monitor and updates actual records with GET only',{skip:!JSDOM},async()=>{const dom=setup(),w=dom.window,calls=[];w.fetch=async(url,options)=>{calls.push({url,options});return{ok:true,status:200,json:async()=>({ok:true,events:[event('needs_review',{observed_at:new Date().toISOString(),decision_needed:'候補を選ぶ'})],nextOffset:null})}};try{w.eval(fs.readFileSync(__dirname+'/v230-request-progress.js','utf8'));await w.CCRequestProgress.pending;assert.equal(w.document.querySelectorAll('[data-request-id]').length,2);assert.match(w.document.querySelector('#requestProgress').textContent,/私の確認待ち/);assert.match(w.document.querySelector('#requestProgress').textContent,/候補を選ぶ/);assert.ok(calls.every(c=>!c.options.method||c.options.method==='GET'));w.document.querySelector('[data-request-tab="monitor"]').click();assert.equal(w.document.getElementById('requestMonitorExisting').hidden,false);w.document.querySelector('[data-request-tab="progress"]').click();assert.equal(w.document.getElementById('requestProgressModal').hidden,false);w.fetch=async()=>{throw Error('offline')};await w.CCRequestProgress.refresh();assert.match(w.document.querySelector('#requestProgress [data-request-list]').textContent,/状況不明/)}finally{w.close()}});
test('DOM fetches every page and does not claim zero requests on malformed/failed response',{skip:!JSDOM},async()=>{const dom=setup(),w=dom.window;let calls=0;w.fetch=async()=>{calls++;return{ok:true,status:200,json:async()=>({ok:true,events:[event('waiting',{request_id:'request-page-'+calls,observed_at:new Date().toISOString()})],nextOffset:calls===1?100:null})}};try{w.eval(fs.readFileSync(__dirname+'/v230-request-progress.js','utf8'));await w.CCRequestProgress.pending;assert.equal(w.CCRequestProgress.rows.length,2);w.fetch=async()=>({ok:true,json:async()=>({ok:true,events:null})});await w.CCRequestProgress.refresh();assert.equal(w.CCRequestProgress.rows.length,2);assert.ok(w.CCRequestProgress.rows.every(x=>x.status==='unknown'))}finally{w.close()}});
const {sqlForRecord}=require('../scripts/request-progress-record.cjs');
test('report writer is namespaced, validates evidence and prevents out-of-order updates',()=>{const {payload}=event('waiting');const sql=sqlForRecord({title:"A's job",...payload});assert.match(sql,/assistant-progress-v1/);assert.match(sql,/A''s job/);assert.match(sql,/occurred_at <= excluded.occurred_at/);assert.throws(()=>sqlForRecord({title:'job',...payload,status:'completed'}),/evidence/);assert.throws(()=>sqlForRecord({title:'job',...payload,status:'needs_review'}),/decision_needed/)});
test('result text stays private in event payload and renders escaped in a collapsible panel',{skip:!JSDOM},async()=>{const dom=setup(),w=dom.window;w.fetch=async()=>({ok:true,json:async()=>({ok:true,events:[event('waiting',{observed_at:new Date().toISOString(),result_text:'原稿\n<script>unsafe()</script>'})],nextOffset:null})});try{w.eval(fs.readFileSync(__dirname+'/v230-request-progress.js','utf8'));await w.CCRequestProgress.pending;const el=w.document.querySelector('#requestProgress .request-result');assert.match(el.textContent,/<script>unsafe/);assert.equal(el.querySelectorAll('script').length,0);el.setAttribute('open','');await w.CCRequestProgress.refresh();assert.equal(w.document.querySelector('#requestProgress .request-result').open,true)}finally{w.close()}});
